### ISSUE TITLE
json without quotes

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-kit-cli#10]
can we have it generate jsons without quotes?

`export CONNECTOR_LEDGERS='{"wallet1."`
to
`export CONNECTOR_LEDGERS={"wallet1."`

**Comment by sharafian** [comment]
The file is interpreted as a shell script, so `CONNECTOR_LEDGERS={"wallet1."` would be interpreted as `CONNECTOR_LEDGERS={wallet1`, which is not valid JSON
